#!/bin/bash
#PBS -N cobaya_cpl_desi_only
#PBS -l nodes=1:ppn=32
#PBS -l walltime=6:00:00
#PBS -l mem=16gb
#PBS -o /dev/null
#PBS -e /dev/null
LOG=/user/p8_group/gr_ADNSS/Swanith/pbs/${PBS_JOBNAME}_${PBS_JOBID%%.*}.out
exec > "$LOG" 2>&1
source /user/p8_group/env/miniforge/etc/profile.d/conda.sh
conda activate /user/p8_group/env/cobaya_env
export PYTHONPATH=$PYTHONPATH:/user/p8_group/cobaya_packages/
export NRANKS=4
export OMP_NUM_THREADS=8
cd /user/p8_group/gr_ADNSS/Swanith
mpirun -n $NRANKS cobaya-run configs/cobaya/cpl_desi_only.yaml -f
